 
export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAILURE = "CREATE_TICKET_FAILURE";

export const GET_USER_TICKETS_REQUEST = "GET_USER_TICKETS_REQUEST";
export const GET_USER_TICKETS_SUCCESS = "GET_USER_TICKETS_SUCCESS";
export const GET_USER_TICKETS_FAILURE = "GET_USER_TICKETS_FAILURE";

export const GET_ALL_TICKETS_REQUEST = "GET_ALL_TICKETS_REQUEST";
export const GET_ALL_TICKETS_SUCCESS = "GET_ALL_TICKETS_SUCCESS";
export const GET_ALL_TICKETS_FAILURE = "GET_ALL_TICKETS_FAILURE";

// New types for Support Agent
export const GET_ASSIGNED_TICKETS_REQUEST = "GET_ASSIGNED_TICKETS_REQUEST";
export const GET_ASSIGNED_TICKETS_SUCCESS = "GET_ASSIGNED_TICKETS_SUCCESS";
export const GET_ASSIGNED_TICKETS_FAILURE = "GET_ASSIGNED_TICKETS_FAILURE";

export const UPDATE_TICKET_STATUS_REQUEST = "UPDATE_TICKET_STATUS_REQUEST";
export const UPDATE_TICKET_STATUS_SUCCESS = "UPDATE_TICKET_STATUS_SUCCESS";
export const UPDATE_TICKET_STATUS_FAILURE = "UPDATE_TICKET_STATUS_FAILURE";

export const ASSIGN_TICKET_REQUEST = "ASSIGN_TICKET_REQUEST";
export const ASSIGN_TICKET_SUCCESS = "ASSIGN_TICKET_SUCCESS";
export const ASSIGN_TICKET_FAILURE = "ASSIGN_TICKET_FAILURE";

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAILURE = "DELETE_TICKET_FAILURE";